"""
提示词模块
将提示词与调用代码分离，方便团队成员分别修改不同部分的提示词逻辑

模块结构：
- thesis_prompts.py: 论文/毕业设计评估相关提示词
- coursework_prompts.py: 课程作业评估相关提示词
- common_prompts.py: 通用提示词（指导文件分析、衍生标准生成等）
"""

from .thesis_prompts import (
    THESIS_SYSTEM_PROMPT,
    THESIS_USER_PROMPT_TEMPLATE,
    THESIS_DETERMINISTIC_SYSTEM_PROMPT,
    THESIS_DETERMINISTIC_USER_PROMPT_TEMPLATE,
    THESIS_EVALUATION_EXPLANATION_SYSTEM_PROMPT,
    THESIS_EVALUATION_EXPLANATION_USER_PROMPT_TEMPLATE,
    INSTITUTIONAL_SYSTEM_PROMPT,
    INSTITUTIONAL_USER_PROMPT_TEMPLATE,
)

from .coursework_prompts import (
    COURSEWORK_SYSTEM_PROMPT,
    COURSEWORK_USER_PROMPT_TEMPLATE,
)

from .common_prompts import (
    GUIDANCE_ANALYSIS_SYSTEM_PROMPT,
    GUIDANCE_ANALYSIS_USER_PROMPT_TEMPLATE,
    DERIVED_STANDARDS_SYSTEM_PROMPT_TEMPLATE,
    DERIVED_STANDARDS_USER_PROMPT_TEMPLATE,
)

__all__ = [
    "THESIS_SYSTEM_PROMPT",
    "THESIS_USER_PROMPT_TEMPLATE",
    "THESIS_DETERMINISTIC_SYSTEM_PROMPT",
    "THESIS_DETERMINISTIC_USER_PROMPT_TEMPLATE",
    "THESIS_EVALUATION_EXPLANATION_SYSTEM_PROMPT",
    "THESIS_EVALUATION_EXPLANATION_USER_PROMPT_TEMPLATE",
    "INSTITUTIONAL_SYSTEM_PROMPT",
    "INSTITUTIONAL_USER_PROMPT_TEMPLATE",
    "COURSEWORK_SYSTEM_PROMPT",
    "COURSEWORK_USER_PROMPT_TEMPLATE",
    "GUIDANCE_ANALYSIS_SYSTEM_PROMPT",
    "GUIDANCE_ANALYSIS_USER_PROMPT_TEMPLATE",
    "DERIVED_STANDARDS_SYSTEM_PROMPT_TEMPLATE",
    "DERIVED_STANDARDS_USER_PROMPT_TEMPLATE",
]
